/**
 * PlaylistCleaner.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetPlaylistTracksResponsePlaylistTrackAlbumImageObject } from './get-playlist-tracks-response-playlist-track-album-image-object';


export interface GetPlaylistTracksResponsePlaylistTrackAlbum { 
    id?: string | null;
    images?: Array<GetPlaylistTracksResponsePlaylistTrackAlbumImageObject> | null;
    name?: string | null;
}

