/**
 * PlaylistCleaner.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetPlaylistResponseExternalUrls } from './get-playlist-response-external-urls';


export interface GetPlaylistResponseAlbumArtist { 
    external_urls?: GetPlaylistResponseExternalUrls;
    href?: string | null;
    id?: string | null;
    name?: string | null;
    type?: string | null;
    uri?: string | null;
}

