/**
 * PlaylistCleaner.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetSongResponseAlbum } from './get-song-response-album';
import { GetSongResponseExternalIds } from './get-song-response-external-ids';
import { GetSongResponseArtist } from './get-song-response-artist';


export interface GetSongResponse { 
    album?: GetSongResponseAlbum;
    artists?: Array<GetSongResponseArtist> | null;
    available_markets?: Array<string> | null;
    duration_ms?: number;
    explicit?: boolean;
    external_ids?: GetSongResponseExternalIds;
    href?: string | null;
    id?: string | null;
    is_playable?: boolean;
    restrictions?: Array<string> | null;
    name?: string | null;
    popularity?: number;
    uri?: string | null;
    is_local?: boolean;
}

