/**
 * PlaylistCleaner.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetPlaylistResponseImageObject } from './get-playlist-response-image-object';
import { GetPlaylistResponseExternalUrls } from './get-playlist-response-external-urls';
import { GetPlaylistResponseRestrictions } from './get-playlist-response-restrictions';
import { GetPlaylistResponseAlbumArtist } from './get-playlist-response-album-artist';


export interface GetPlaylistResponseAlbum { 
    album_type?: string | null;
    total_tracks?: number;
    available_markets?: Array<string> | null;
    external_urls?: GetPlaylistResponseExternalUrls;
    href?: string | null;
    id?: string | null;
    images?: Array<GetPlaylistResponseImageObject> | null;
    name?: string | null;
    release_date?: string | null;
    release_date_precision?: string | null;
    restrictions?: GetPlaylistResponseRestrictions;
    type?: string | null;
    uri?: string | null;
    artists?: Array<GetPlaylistResponseAlbumArtist> | null;
}

