/**
 * PlaylistCleaner.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetPlaylistTracksResponsePlaylistTrackData } from './get-playlist-tracks-response-playlist-track-data';
import { GetPlaylistTracksResponsePlaylistTrackAddedBy } from './get-playlist-tracks-response-playlist-track-added-by';


export interface GetPlaylistTracksResponsePlaylistTrack { 
    added_at?: string;
    added_by?: GetPlaylistTracksResponsePlaylistTrackAddedBy;
    is_local?: boolean;
    track?: GetPlaylistTracksResponsePlaylistTrackData;
    position?: number;
}

