/**
 * PlaylistCleaner.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetPlaylistResponseTrackAddedBy } from './get-playlist-response-track-added-by';
import { GetPlaylistResponseTrackData } from './get-playlist-response-track-data';


export interface GetPlaylistResponseTrack { 
    added_at?: string;
    added_by?: GetPlaylistResponseTrackAddedBy;
    is_local?: boolean;
    track?: GetPlaylistResponseTrackData;
}

