/**
 * PlaylistCleaner.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetCurrentUsersProfileResponseExplicitContent } from './get-current-users-profile-response-explicit-content';
import { GetCurrentUsersProfileResponseFollower } from './get-current-users-profile-response-follower';
import { GetCurrentUsersProfileResponseImage } from './get-current-users-profile-response-image';


export interface GetCurrentUsersProfileResponse { 
    country?: string | null;
    display_name?: string | null;
    email?: string | null;
    explicit_content?: GetCurrentUsersProfileResponseExplicitContent;
    spotify_external_url?: string | null;
    followers?: GetCurrentUsersProfileResponseFollower;
    href?: string | null;
    id?: string | null;
    images?: Array<GetCurrentUsersProfileResponseImage> | null;
    product?: string | null;
    type?: string | null;
    uri?: string | null;
}

