/**
 * PlaylistCleaner.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetPlaylistResponseImageObject } from './get-playlist-response-image-object';
import { GetPlaylistResponsePlaylistOwner } from './get-playlist-response-playlist-owner';
import { GetPlaylistResponseExternalUrls } from './get-playlist-response-external-urls';
import { GetPlaylistResponseFollowers } from './get-playlist-response-followers';
import { GetPlaylistResponseTrack } from './get-playlist-response-track';


export interface GetPlaylistResponse { 
    collaborative?: boolean;
    description?: string | null;
    external_urls?: GetPlaylistResponseExternalUrls;
    href?: string | null;
    id?: string | null;
    followers?: GetPlaylistResponseFollowers;
    images?: Array<GetPlaylistResponseImageObject> | null;
    name?: string | null;
    owner?: GetPlaylistResponsePlaylistOwner;
    public?: boolean;
    snapshot_id?: string | null;
    tracks?: GetPlaylistResponseTrack;
    type?: string | null;
    uri?: string | null;
}

