/**
 * PlaylistCleaner.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetPlaylistResponseImageObject } from './get-playlist-response-image-object';
import { GetPlaylistResponseExternalUrls } from './get-playlist-response-external-urls';
import { GetPlaylistResponseFollowers } from './get-playlist-response-followers';


export interface GetPlaylistResponseArtist { 
    external_urls?: GetPlaylistResponseExternalUrls;
    followers?: GetPlaylistResponseFollowers;
    genres?: Array<string> | null;
    href?: string | null;
    id?: string | null;
    images?: Array<GetPlaylistResponseImageObject> | null;
    name?: string | null;
    popularity?: number;
    type?: string | null;
    uri?: string | null;
}

