/**
 * PlaylistCleaner.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetPlaylistResponseExternalUrls } from './get-playlist-response-external-urls';
import { GetPlaylistResponseRestrictions } from './get-playlist-response-restrictions';
import { GetPlaylistResponseAlbum } from './get-playlist-response-album';
import { GetPlaylistResponseExternalIds } from './get-playlist-response-external-ids';
import { GetPlaylistResponseArtist } from './get-playlist-response-artist';


export interface GetPlaylistResponseTrackData { 
    album?: GetPlaylistResponseAlbum;
    artists?: Array<GetPlaylistResponseArtist> | null;
    available_markets?: Array<string> | null;
    disc_number?: number;
    duration_ms?: number;
    explicit?: boolean;
    external_ids?: GetPlaylistResponseExternalIds;
    external_urls?: GetPlaylistResponseExternalUrls;
    href?: string | null;
    id?: string | null;
    is_playable?: boolean;
    restrictions?: GetPlaylistResponseRestrictions;
    name?: string | null;
    popularity?: number;
    preview_url?: string | null;
    track_number?: number;
    type?: string | null;
    uri?: string | null;
    is_local?: boolean;
}

