export * from './playlists.service';
import { PlaylistsServiceApi } from './playlists.service';
export * from './playlists.serviceInterface';
export * from './songs.service';
import { SongsServiceApi } from './songs.service';
export * from './songs.serviceInterface';
export * from './users.service';
import { UsersServiceApi } from './users.service';
export * from './users.serviceInterface';
export const APIS = [PlaylistsServiceApi, SongsServiceApi, UsersServiceApi];
