/**
 * PlaylistCleaner.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GetPlaylistDuplicatesResponse } from '../model/models';
import { GetPlaylistResponse } from '../model/models';
import { GetPlaylistTracksResponse } from '../model/models';
import { ProblemDetails } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PlaylistsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param playlistId 
     */
    apiV1PlaylistsPlaylistIdDuplicatesGet(playlistId: string, extraHttpRequestParams?: any): Observable<GetPlaylistDuplicatesResponse>;

    /**
     * 
     * 
     * @param playlistId 
     */
    apiV1PlaylistsPlaylistIdGet(playlistId: string, extraHttpRequestParams?: any): Observable<GetPlaylistResponse>;

    /**
     * 
     * 
     * @param playlistId 
     */
    apiV1PlaylistsPlaylistIdTracksGet(playlistId: string, extraHttpRequestParams?: any): Observable<GetPlaylistTracksResponse>;

    /**
     * 
     * 
     * @param playlistId 
     * @param trackId 
     * @param trackIndex 
     */
    apiV1PlaylistsPlaylistIdTracksTrackIdDelete(playlistId: string, trackId: string, trackIndex?: number, extraHttpRequestParams?: any): Observable<{}>;

}
