/**
 * PlaylistCleaner.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GetCurrentUsersProfileResponse } from '../model/models';
import { GetUserProfileResponse } from '../model/models';
import { ProblemDetails } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UsersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    apiV1UsersMeGet(extraHttpRequestParams?: any): Observable<GetCurrentUsersProfileResponse>;

    /**
     * 
     * 
     * @param userId 
     */
    apiV1UsersUserIdProfileGet(userId: string, extraHttpRequestParams?: any): Observable<GetUserProfileResponse>;

}
